package codetest.codetest.repositories;

import org.springframework.data.repository.CrudRepository;

import codetest.codetest.entities.Calculation;


/**
 * Repository class taking advantage of CrudRepository
 */
public interface CalcualtionRepository extends CrudRepository<Calculation, Long> {

    // Autogenerated query methods if need more methods see
    // https://docs.spring.io/spring-data/jpa/docs/current/reference/html/
}